services:
  app:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=624562
      - DB_NAME=learn-6
      - JWT_SECRET=kafjaksjfoje154646fesafesfaefea64f6ae4f684af68e
      - NODE_ENV=development
      - EMAIL_SERVICE_URL=http://python-mailer:8000
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
      - python-mailer
    networks:
      - backend-network

    volumes:
      - ./Server:/app # ربط كود السيرفر
      - /app/node_modules # (Anonymous Volume) عشان يحمي المكاتب اللي جوه الحاوية
      - /app/dist # (Anonymous Volume) عشان يحمي ملفات الـ build اللي جوه الحاوية
      - ./Server/uploads:/app/uploads # ربط مجلد الصور عشان تفضل موجودة

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "624562"
      POSTGRES_DB: learn-6
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend-network

  python-mailer:
    container_name: mailer
    build:
      context: ./Server/Microservices/Email/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # ملف الإعدادات من الجذر
      - ./Server/uploads:/app/uploads:ro # وصول Nginx للصور لعرضها
      - ./Client:/usr/share/nginx/html:ro # ملفات الفرونت إند
    depends_on:
      - app
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres:
  webroot:
